version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - emanet

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - emanet

networks:
  emanet:
    driver: bridge